[build]
    publish = "public/"
    command = "./scripts/netlify.sh"

[build.environment]
    HUGO_VERSION = "0.47.1"
    NODE_ENV = "production"
    NPM_CONFIG_PRODUCTION = "false"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "same-origin"
        Strict-Transport-Security = "max-age=5184000"
